CREATE TABLE properties (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  unitNumber VARCHAR(100) NULL,
  houseNumber VARCHAR(100) NOT NULL,
  street VARCHAR(100) NOT NULL,
  PRIMARY KEY ( id )
);
